SkygearIO/skygear-SDK-JS

lib/container.js, test/container.js
connect oursky/skygear-SDK-JS#162
=> Clear current user after logout

lib/acl.js, lib/container.js, lib/record.js, lib/role.js, test/acl.js, test/container.js, test/record.js, test/reference.js, test/role.js
connect oursky/skygear-SDK-JS#156
=> Fix wrong representation of public access

lib/util.js, test/record.js
=> Add deserialization of reference type

lib/pubsub.js
=> Add exception for invalid pubsub data

example/record.html, lib/database.js, lib/query.js, test/query.js
=> Support `page` property on query

lib/container.js, test/container.js, test/user.js
connect SkygearIO/skygear-server#111
=> Add API to get current user from server

lib/query_result.js, lib/record.js, lib/relation.js
=> Fix crash on IE 10 when using `Array.from`

lib/container.js, test/container.js
=> Add getUsersByUsername to container 

example/index.html, lib/container.js, test/container.js
The correct behavior is to handle the auth response (e.g. use new access
token) and to return the user object.
connects #90
connects #91
=> Fix change password not handling auth response

lib/relation.js, test/relation.js
=> Remove relation success return array of ids

lib/record.js, test/record.js
=> Accept same type of record instance in Record constructor

bin.js, lib/bin.js, lib/cloud/registry.js, lib/cloud/transport/common.js, lib/cloud/transport/http.js
- return the init to server
- call lambda
- call timer
- call hook
connects #87
=> Add initial http transport implementation

.dockerignore, .gitignore, .travis.yml, Dockerfile-development, Makefile, docker-compose.dev.yml, docker-compose.yml, package.json, scripts/deploy.sh, scripts/docker-images/nodedev/Dockerfile, scripts/docker-images/nodedev/Makefile, scripts/docker-images/nodedev/README.md, scripts/docker-images/release/Dockerfile, scripts/docker-images/release/Dockerfile-onbuild, scripts/docker-images/release/Makefile
=> Docker image for cloud code

lib/cloud/registry.js, lib/cloud/transport/common.js, test/cloud/registry.js, test/cloud/transport/common.js
And add various test case
connects #105
=> Provide Record instance to DB hook

.eslintrc, lib/cloud/index.js, lib/cloud/transport/common.js
=> Provide pq.pool as the third argument on DB hook

lib/bin.js, lib/cloud/index.js, lib/cloud/registry.js, lib/cloud/settings.js, lib/cloud/skyconfig.js, lib/cloud/transport/common.js, lib/cloud/transport/http.js, test/cloud/registry.js, test/cloud/transport/common.js
=> Support plugin event

lib/cloud/index.js, lib/cloud/registry.js, lib/cloud/transport/common.js, lib/cloud/transport/http.js, test/cloud/transport/common.js
=> Js Auth provider in cloud code

docker-compose.yml, lib/cloud/container.js, lib/cloud/index.js, lib/container.js
The `pg` and `settings` module are not exposed in skygear cloud package. Furthermore, cloud code need a container that can be instantiated and be configured for cloud code use (such as master key and impersonate another user).
=> Expose pg pool, settings and CloudCodeContainer

lib/store.js, lib/util.js, package.json
=> Remove dep on localforage

asset.js, lib/asset_collect.js, lib/bin.js, lib/cloud/asset.js, lib/cloud/index.js, lib/cloud/registry.js, lib/cloud/settings.js, lib/cloud/transport/common.js, package.json, test/cloud/registry.js
- Providing `staticAsset` for declaring local files as static assets
- Server static asset during develop if `SERVE_STATIC_ASSETS` is true
- Provide `skyegar-asset` command to Collect local asset in cloud deployment
connects #97
=> Support static asset

.babelrc, lib/cloud/index.js, lib/cloud/transport/http.js, lib/container.js, lib/error.js, test/error.js
=> Return error to skygear-server in correct format

lib/cache.js, lib/container.js, lib/database.js, lib/store.js, test/cache.js, test/store.js
=> Rewrite cache and store

lib/container.js, test/container.js
connect SkygearIO/skygear-server#245
connect SkygearIO/skygear-server#249
=> Support unregister device

lib/cloud/index.js
=> Add class doc for user context

lib/container.js, test/container.js
connect SkygearIO/skygear-server#239
=> Accept bundle name when register device

lib/cloud/asset.js, lib/cloud/settings.js, package.json, test/asset.js
=> Add url signing function to cloud

lib/cloud/container.js, lib/container.js, test/cloud/container.js
connect https://github.com/SkygearIO/skygear-SDK-JS/issues/186
=> Fix issue with shared user between containers

.travis.yml, Makefile, esdoc.json, lib/cloud/asset.js, package.json
=> Fix esdoc generation

lib/cloud/pg.js, lib/cloud/settings.js
=> Allow config of pg pool size

lib/cloud/container.js
=> Support plugin only request during plugin initialization

.eslintrc, gulp/tasks/build.js, packages/skygear-core/lib/acl.js, packages/skygear-core/lib/auth.js, packages/skygear-core/lib/cache.js, packages/skygear-core/lib/cloud/asset.js, packages/skygear-core/lib/cloud/container.js, packages/skygear-core/lib/cloud/registry.js, packages/skygear-core/lib/container.js, packages/skygear-core/lib/database.js, packages/skygear-core/lib/pubsub.js, packages/skygear-core/lib/push.js, packages/skygear-core/lib/react-native/index.js, packages/skygear-core/lib/react-native/push.js, packages/skygear-core/lib/record.js, packages/skygear-core/lib/relation.js, packages/skygear-core/lib/store.js, packages/skygear-core/test/asset.js, packages/skygear-core/test/cloud/container.js, packages/skygear-core/test/container.js, packages/skygear-core/test/push.js
- Fix the gulp task to properly run the lint
- Fix import bugs detected by lint
- Add arrow-space rules
=> Fix the gulp task and update lint rules

example/index.html, example/pubsub.html, example/record.html, example/role-acl.html, example/user.html, gulp/tasks/test.js, package.json, packages/skygear-forgot-password/lib/index.js, packages/skygear-forgot-password/package.json, packages/skygear/lib/index.js, packages/skygear/package.json
connect #237 
https://github.com/SkygearIO/features/issues/70
=> Add forgot password functions to skygear.auth

packages/skygear-core/lib/cloud/asset.js, packages/skygear-core/package.json, packages/skygear-core/test/asset.js
refs skygeario/skygear-server#427
=> Correctly signed URL for fs aseet

packages/skygear-core/lib/pubsub.js
=> Add back pubsub.reconfigure()

.travis.yml, Makefile, scripts/deploy.sh
Examples:
* https://docs.skygear.io/js/reference/v1.1.0/
* https://docs.skygear.io/js/reference/latest/
* https://docs.skygear.io/js/reference/canary/
=> Upload doc prefixed with version for CI

esdoc-plugins/injectTo/index.js
=> Update esdoc plugin to esdoc 1.0.1 syntax

example/cloud/README.md, example/cloud/docker-compose.yml, example/cloud/index.js, example/cloud/package.json
Follow up https://github.com/SkygearIO/skygear-SDK-JS/pull/272
=> Add minimal cloud example

.travis.yml, Makefile, gulp/context.js, packages/skygear-core/lib/container.js
=> Inject version string in Makefile, and include the version in request header

packages/skygear-core/lib/acl.js, packages/skygear-core/lib/asset.js, packages/skygear-core/lib/auth.js, packages/skygear-core/lib/container.js, packages/skygear-core/lib/database.js, packages/skygear-core/lib/error.js, packages/skygear-core/lib/geolocation.js, packages/skygear-core/lib/pubsub.js, packages/skygear-core/lib/push.js, packages/skygear-core/lib/query.js, packages/skygear-core/lib/record.js, packages/skygear-core/lib/reference.js, packages/skygear-core/lib/relation.js, packages/skygear-core/lib/role.js, packages/skygear-core/lib/store.js, packages/skygear-core/lib/type.js
=> Update api reference

packages/skygear-core/lib/container.js, packages/skygear-core/test/container.js, packages/skygear-core/test/mock/superagent.js
=> Add Content-Type: application/json to request made by container 

example/push.html, packages/skygear-core/lib/push.js, packages/skygear-core/test/push.js
=> Add sendToUser and sendToDevice

packages/skygear-core/lib/database.js
refs SkygearIO/skygear-doc#529
=> Fix broken link in doc

example/pubsub.html, example/record.html
=> Use bootstrap 3 to style pubsub html page

example/sso.html, packages/skygear-core/lib/store.js, packages/skygear-sso/lib/index.js, packages/skygear-sso/lib/oauth.js, packages/skygear-sso/lib/observer.js, packages/skygear-sso/lib/util.js, packages/skygear-sso/package.json, packages/skygear-sso/test/oauth.js, packages/skygear-sso/test/observer.js, packages/skygear/lib/index.js, packages/skygear/package.json
=> Support loginOAuthProviderWithRedirect flow

example/sso.html, packages/skygear-core/lib/store.js, packages/skygear-sso/lib/index.js, packages/skygear-sso/lib/oauth.js, packages/skygear-sso/test/oauth.js
=> Sso link flow

example/index.html, packages/skygear-sso/lib/custom_token.js, packages/skygear-sso/lib/index.js, packages/skygear-sso/package-lock.json, packages/skygear-sso/test/custom_token.js
=> Implement loginWithCustomToken

packages/skygear/lib/index.js, packages/skygear/react-native.js
Fix missing loginWithCustomToken api in react-native container
connect #366
=> Inject sso and forgot password to react native container

packages/skygear-core/lib/auth.js, packages/skygear-core/test/auth.js, packages/skygear-sso/package-lock.json
connect skygeario/skygear-server#524
=> Fix signup profile serialization

packages/skygear-core/lib/auth.js, packages/skygear-core/test/auth.js
=> Support enable/disable user account

example/index.html, example/verify.html, packages/skygear-forgot-password/lib/index.js, packages/skygear-forgot-password/test/index.js
=> Implement request verification and submit code

packages/skygear-core/lib/auth.js, packages/skygear-core/test/auth.js
=> Add admin prefix to disable/enable user functions

gulp/context.js, packages/skygear-core/lib/container.js
=> Remove default endpoint in container

packages/skygear-core/lib/auth.js, packages/skygear-core/test/auth.js
=> Handle offline logout clear user info

packages/skygear-sso/package-lock.json, packages/skygear-sso/package.json
Related issues:
https://github.com/hapijs/hoek/issues/230#issuecomment-384816142
https://github.com/hapijs/hoek/issues/247
=> Update `hoek` dependencies of `mock-browser` for security updates

packages/skygear-core/examples/lambda-types.js, packages/skygear-core/lib/asset.js, packages/skygear-core/lib/cloud/transport/common.js, packages/skygear-core/lib/container.js, packages/skygear-core/lib/database.js, packages/skygear-core/lib/record.js, packages/skygear-core/lib/util.js, packages/skygear-core/test/asset.js, packages/skygear-core/test/container.js, packages/skygear-core/test/record.js, packages/skygear-core/test/util.js
=> Add Lambda support for Skygear Data Type in Cloud

example/sso.html, packages/skygear-core/lib/container.js, packages/skygear-core/lib/error.js, packages/skygear-core/lib/push.js, packages/skygear-core/test/auth.js, packages/skygear-core/test/container.js, packages/skygear-core/test/push.js, packages/skygear-sso/lib/util.js, packages/skygear-sso/test/oauth.js, packages/skygear-sso/test/observer.js
=> Return SkygearError instead of object

packages/skygear-core/lib/database.js, packages/skygear-core/package.json
connect oursky/skygear-content-manager#269
=> Throw asset s3 error

packages/skygear-core/lib/database.js, packages/skygear-core/package.json
=> Throw asset s3 error (patch for v1)

example/record.html, packages/skygear-core/lib/database.js, packages/skygear-core/lib/record.js, packages/skygear-core/test/database.js, packages/skygear-core/test/record.js, packages/skygear-sso/package-lock.json
=> Update record APIs for consistency

packages/skygear-core/lib/cloud/container.js, packages/skygear-core/lib/cloud/index.js
connect oursky/skygear-support#56
=> Add util functions helping publish event in cloud code

packages/skygear-core/lib/auth.js, packages/skygear-core/lib/pubsub.js, packages/skygear-core/test/container.js
=> update js sdk for next

package-lock.json, package.json, packages/skygear-sso/lib/custom_token.js, packages/skygear-sso/lib/oauth.js, packages/skygear-sso/test/custom_token.js, packages/skygear-sso/test/oauth.js
connects #475 
For fixing "internalBinding is not defined" error on node 10.14.2, I update `package.json` and force "natives" version to 1.1.6. Don't know if it is a good approach, let me know if there is other better solutions.
=> Update oauth container for skygear next

packages/skygear-sso/lib/oauth.js, packages/skygear-sso/lib/observer.js, packages/skygear-sso/test/oauth.js, packages/skygear-sso/test/observer.js
=> v1: SSO fix other origin message

example/user.html, packages/skygear-core/lib/auth.js, packages/skygear-core/test/auth.js
=> next: Support updateMetadata API

example/index.html, example/sso.html, example/user.html, example/verify.html, packages/skygear-core/lib/auth.js, packages/skygear-core/lib/user.js, packages/skygear-core/test/auth.js, packages/skygear-forgot-password/test/index.js, packages/skygear-sso/test/custom_token.js, packages/skygear-sso/test/oauth.js
=> next: Update for login ids

packages/skygear-core/lib/cloud/pg.js, packages/skygear-core/lib/cloud/pgurl.js, packages/skygear-core/test/cloud/pgurl.js
=> fix(pq-auth): handle undefined auth param

packages/skygear-core/src/container.ts, packages/skygear-core/src/types.ts, packages/skygear-node-client/src/index.ts, packages/skygear-react-native/src/index.ts, packages/skygear-web/src/container.ts, packages/skygear-web/src/index.ts
=> Introduce options and default values for containers constructor

package-lock.json, packages/example/package-lock.json, packages/example/src/index.html, packages/example/src/session.html, packages/skygear-core/src/base64.test.ts, packages/skygear-core/src/base64.ts, packages/skygear-core/src/client.ts, packages/skygear-core/src/container.ts, packages/skygear-core/src/encoding.ts, packages/skygear-core/src/storage.test.ts, packages/skygear-core/src/storage.ts, packages/skygear-core/src/types.ts, packages/skygear-node-client/package-lock.json, packages/skygear-node-client/src/index.ts, packages/skygear-react-native/package-lock.json, rollup.config.js
=> Update for new session mechanism

packages/skygear-core/src/client.ts, packages/skygear-core/src/error.ts
=> Handle unexpected errors correctly

packages/example/src/session.html, packages/skygear-core/src/client.ts, packages/skygear-core/src/container.ts, packages/skygear-core/src/encoding.ts, packages/skygear-core/src/storage.test.ts, packages/skygear-core/src/types.ts, packages/skygear-node-client/src/index.ts
=> Update session API

packages/skygear-web/src/container.ts
Depends on https://github.com/SkygearIO/skygear-server/pull/1039
=> Return user in link

packages/example/src/authenticator.html, packages/example/src/bearertoken.html, packages/example/src/fetch.html, packages/example/src/forgotpassword.html, packages/example/src/login.html, packages/example/src/oob.html, packages/example/src/recoverycode.html, packages/example/src/session.html, packages/example/src/signup.html, packages/example/src/sso.html, packages/example/src/totp.html, packages/example/src/user.html, packages/example/src/verification.html, packages/skygear-node-client/src/index.ts, packages/skygear-react-native/src/index.ts, packages/skygear-web/src/index.iife.ts, packages/skygear-web/src/index.ts, rollup.config.js
connect #519 
Since https://github.com/SkygearIO/skygear-SDK-JS/pull/523 added many examples, this PR need to rebase after it is merged.
=> defaultContainer and ES6 default export

packages/skygear-core/src/container.ts
=> Allow ignoring error in logout

packages/example/src/totp.html, packages/skygear-core/src/client.ts, packages/skygear-core/src/container.ts, packages/skygear-core/src/types.ts
connect https://github.com/SkygearIO/skygear-server/issues/1072
connect https://github.com/SkygearIO/skygear-SDK-JS/issues/533
=> MFA follow up

packages/example/src/index.html, packages/example/src/verification.html, packages/skygear-core/src/client.ts, packages/skygear-core/src/container.ts
=> Add requestPhoneVerification

packages/skygear-core/src/client.ts, packages/skygear-core/src/container.ts, packages/skygear-core/src/encoding.ts, packages/skygear-core/src/error.ts, packages/skygear-core/src/storage.ts, packages/skygear-core/src/types.ts, packages/skygear-core/src/validation.test.ts, packages/skygear-core/src/validation.ts
=> Add validation error typings

packages/example/src/login.html, packages/example/src/signup.html, packages/skygear-core/src/client.ts, packages/skygear-core/src/container.ts, packages/skygear-core/src/encoding.ts, packages/skygear-core/src/storage.test.ts, packages/skygear-core/src/types.ts, packages/skygear-web/src/container.ts
=> Remove realm from APIs

packages/skygear-core/src/container.ts, packages/skygear-core/src/error.ts, packages/skygear-core/src/imageprocessing.ts, packages/skygear-core/src/types.ts, packages/skygear-core/src/validation.ts, packages/skygear-node-client/src/index.ts, packages/skygear-react-native/src/index.ts, packages/skygear-web/src/container.ts, packages/skygear-web/src/index.ts
=> Document important functions & types

packages/example/src/identity.html, packages/example/src/index.html, packages/skygear-core/src/client.ts, packages/skygear-core/src/container.ts
=> Add identity APIs

packages/skygear-core/src/base64.test.ts, packages/skygear-core/src/base64.ts, packages/skygear-core/src/client.ts, packages/skygear-core/src/types.ts, packages/skygear-react-native/android/build.gradle, packages/skygear-react-native/android/src/main/AndroidManifest.xml, packages/skygear-react-native/android/src/main/java/io/skygear/reactnative/OAuthRedirectActivity.java, packages/skygear-react-native/android/src/main/java/io/skygear/reactnative/SGSkygearReactNativeModule.java, packages/skygear-react-native/android/src/main/java/io/skygear/reactnative/SGSkygearReactNativePackage.java, packages/skygear-react-native/ios/SGSkygearReactNative.h, packages/skygear-react-native/ios/SGSkygearReactNative.m, packages/skygear-react-native/ios/SGSkygearReactNative.xcodeproj/project.pbxproj, packages/skygear-react-native/ios/SGSkygearReactNative.xcworkspace/contents.xcworkspacedata, packages/skygear-react-native/package-lock.json, packages/skygear-react-native/package.json, packages/skygear-react-native/skygear-react-native.podspec, packages/skygear-react-native/src/index.ts, packages/skygear-react-native/src/nativemodule.ts, packages/skygear-react-native/src/pkce.ts, packages/skygear-react-native/src/url.test.ts, packages/skygear-react-native/src/url.ts, packages/skygear-web/src/pkce.ts
=> React Native oauth and Sign in with Apple

README.md, packages/example/index.js, packages/example/src/asset.html, packages/example/src/authenticator.html, packages/example/src/bearertoken.html, packages/example/src/fetch.html, packages/example/src/forgotpassword.html, packages/example/src/identity.html, packages/example/src/login.html, packages/example/src/oob.html, packages/example/src/recoverycode.html, packages/example/src/session.html, packages/example/src/signup.html, packages/example/src/sso.html, packages/example/src/totp.html, packages/example/src/user.html, packages/example/src/verification.html, packages/skygear-core/src/client.test.ts, packages/skygear-core/src/client.ts, packages/skygear-core/src/container.ts, packages/skygear-node-client/src/index.ts, packages/skygear-react-native/src/index.ts, packages/skygear-web/src/container.ts
=> Support gear and app endpoints config

packages/skygear-react-native/android/build.gradle, packages/skygear-react-native/android/src/main/java/io/skygear/reactnative/SGCustomTabsHelper.java, packages/skygear-react-native/android/src/main/java/io/skygear/reactnative/SGSkygearReactNativeModule.java
=> Use Chrome Custom Tabs if available

packages/example/index.js, packages/example/src/authui.html, packages/example/src/index.html, packages/skygear-core/src/client.ts, packages/skygear-core/src/container.ts, packages/skygear-core/src/encoding.ts, packages/skygear-core/src/storage.ts, packages/skygear-core/src/types.ts, packages/skygear-core/src/url.test.ts, packages/skygear-core/src/url.ts, packages/skygear-react-native/android/src/main/java/io/skygear/reactnative/SGSkygearReactNativeModule.java, packages/skygear-react-native/ios/SGSkygearReactNative.m, packages/skygear-react-native/src/index.ts, packages/skygear-react-native/src/nativemodule.ts, packages/skygear-web/src/container.ts
=> React native authorize with oidc flow

packages/example/src/authui.html, packages/skygear-core/src/container.ts, packages/skygear-react-native/src/index.ts, packages/skygear-web/src/container.ts
=> Authui namespace

packages/skygear-core/src/container.ts, packages/skygear-core/src/error.ts, packages/skygear-core/src/types.ts
=> Update MFA step names

packages/example/src/authenticator.html, packages/example/src/authui.html, packages/example/src/bearertoken.html, packages/example/src/forgotpassword.html, packages/example/src/identity.html, packages/example/src/login.html, packages/example/src/oob.html, packages/example/src/recoverycode.html, packages/example/src/session.html, packages/example/src/signup.html, packages/example/src/sso.html, packages/example/src/totp.html, packages/example/src/user.html, packages/example/src/verification.html, packages/skygear-core/src/container.ts, packages/skygear-react-native/src/index.ts, packages/skygear-web/src/container.ts
=> Update namespace to `classAuth` for api and `auth` for auth ui

README.md, packages/example/index.js
=> Update example instructions

packages/skygear-core/src/types.ts
=> Remove unused fields in OIDCConfiguration

packages/skygear-core/src/container.ts
ref SkygearIO/skygear-server#1372
=> Allow configuring OIDC prompt parameter

package-lock.json, package.json, rollup.config.js
=> Derive rollup external from package.json

packages/skygear-react-native/src/index.ts
=> Make content-type required in react native

packages/skygear-core/src/container.ts, packages/skygear-core/src/encoding.ts, packages/skygear-core/src/storage.test.ts, packages/skygear-core/src/storage.ts, packages/skygear-core/src/types.ts
ref SkygearIO/skygear-server#1424
=> Update identity handling

packages/skygear-core/src/encoding.ts, packages/skygear-core/src/storage.test.ts, packages/skygear-core/src/types.ts
ref SkygearIO/skygear-server#1425
=> Add anonymous user flag

packages/skygear-core/src/container.ts
=> Add options for UI locales
